apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-website-deployment
  labels:
    app: portfolio-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portfolio-website
  template:
    metadata:
      labels:
        app: portfolio-website
    spec:
      containers:
      - name: portfolio-website-container
        image: gcr.io/your-project-id/portfolio-website:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-website-service
spec:
  type: LoadBalancer
  selector:
    app: portfolio-website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
